# script with Blocks and Resources 
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 2.21.0"
}
}
}

provider "docker" {}

resource "docker_image" "nginx" {
 name         = "nginx:latest"
 keep_locally = false
}

resource "docker_container" "nginx" {
 image = docker_image.nginx.latest
 name  = "tutorial"
 ports {
   internal = 80
   external = 80
 }
}

# terraform init -> Initializes a new or existing Terraform working directory by downloading and installing any required providers and modules, 
# initializing the backend, and downloading any necessary plugins.

# terraform plan -> Generates an execution plan that shows what actions Terraform will take to reach the desired state specified in the configuration file.
# This command also reports any changes that will be made to the infrastructure.

# terraform apply -> Executes the actions proposed in the execution plan generated by terraform plan. This command provisions and configures the
# infrastructure defined in the configuration file.